### ISSUE TITLE
Multi-GPU support?

### ISSUE THREAD

**Issue by quarterturn** [bigscience-workshop/petals#203]
Are there docs on enabling multi-GPU support? If not, can we have a feature request to add this? Per the default install instructions, I'm only seeing GPU0 being utilized. Maybe it's as simple as adding a "device_map='auto'" in the model creation?

**Comment by borzunov** [comment]
Hi @quarterturn!

Currently, **the recommended way** to use multiple GPUs is to run a separate Petals server for each of them. For each server, you need to restrict the GPUs it can use by specifying the `CUDA_VISIBLE_DEVICES=N` env variable, where `N` is the GPU number (starting with 0).

This is a temporary solution, and we currently work on intra-host tensor parallelism for the Petals server. Once it's ready, the server will automatically use all available GPUs (unless you explicitly tell it not to) and run computations in parallel. Our benchmarks show that it may give almost linear speedup (e.g., the requests will be processed ~1.9x faster on 2 GPUs, ~3.8x faster on 4 GPUs, and so on).

We already have **experimental** code for tensor parallelism, but it is not integrated well yet and doesn't work properly with all GPU configurations. Currently, it gives ~1.9x speedup on 2x 1080 Ti, but slows the server down if you use 4x 1080 Ti or 2x high-end GPUs (e.g., 2x A100). It also does not support loading the model in 8-bit, so you'd be able to only load in 16-bit format (= each block will consume 2x more GPU memory).

If you'd like to try this experimental feature, you can run a server with the `--tensor_parallel_devices cuda:0 cuda:1` flag (specify as many `cuda:N` as the number of GPUs you'd like to use). The 16-bit format will be chosen automatically in this case.

**Important:** If you do that, please ensure that the compute RPS measured in this case is indeed faster than the RPS you have without tensor parallelism. Due to the code compatibility issues, tensor-parallelism may lead to huge slowdown on some GPUs. In this case, you'll end up running unusually slow servers that will have a very negative effect on the performance of the public swarm. We'd be interested if you can share your GPU model and the RPS you got with and without tensor parallelism.

If tensor-parallelism turns out to be slower for your setup, please run separate servers instead until we fix it.

**Comment by quarterturn** [comment]
I get the following on startup via a single instance:
```
Jan 11 07:55:48.693 [INFO] Forward pass throughput (Tesla P100-PCIE-16GB GPU, 8-bit): 155.6 RPS
```
I'll let all four blocks load and see if something else gets reported, then I'll test with '--tensor_parallel_devices'

**Comment by quarterturn** [comment]
Looking good:
```
Forward pass throughput (2x Tesla P100-PCIE-16GB GPU, torch.bfloat16): 490.8 RPS

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     91242      C   python                          15126MiB |
|    1   N/A  N/A     91242      C   python                          15126MiB |
+-----------------------------------------------------------------------------+
```

**Comment by borzunov** [comment]
Amazing! Thanks for taking the time to contribute compute.

**Comment by quarterturn** [comment]
Looks like it might have gotten a block to process and then caught an exception:

```
Jan 11 11:29:35.863 [ERROR] [hivemind.moe.server.runtime.run:104] Caught indices should be either on cpu or on the same device as the indexed tensor (cuda:1), attempting to recover
Traceback (most recent call last):
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/moe/server/runtime.py", line 91, in run
    outputs = pool.process_func(*batch)
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/backend.py", line 88, in inference_step
    self._reorder_cache_inplace(cache_tensors, hypo_ids)
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/backend.py", line 98, in _reorder_cache_inplace
    cache_tensor[...] = cache_tensor[hypo_ids]  # in-place reorder cache by hypo ids
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
Jan 11 11:29:35.867 [INFO] rpc_inference.close(blocks=54:58, remote_peer=...snyhNM)
Jan 11 11:29:35.867 [WARN] [hivemind.p2p.p2p_daemon._process_stream:436] Handler failed with the exception:
Traceback (most recent call last):
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 427, in _process_stream
    async for response in handler(_read_stream(), context):
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/p2p/p2p_daemon.py", line 525, in _stream_handler
    async for item in output:
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/petals/server/handler.py", line 181, in rpc_inference
    (hidden_states,) = await backend.inference_pool.submit_task(
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/site-packages/hivemind/utils/mpfuture.py", line 294, in __await__
    return super().result()
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/qtrn/anaconda3/envs/petals/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cuda:1)
```
