### ISSUE TITLE
Is Petals the Solution that ChatGPT needs?

### ISSUE THREAD

**Issue by gssakash** [bigscience-workshop/petals#223]
I recently found out about Petals and the way it optimizes the process of running LLM models on your local machine through a Bit-Torrent style-based approach seemed very innovative to me.

Right now, it is estimated that it costs over a 100k dollars to run ChatGPT daily and I was wondering if this cost could be brought down using solutions like Petal as this could also help the environment by lowering a very massive footprint that this complex operation would cause

**Comment by justheuristic** [comment]
This is a complicated question - and i'm afraid we won't find a definitive answer within this issue. I can share my own point of view  - other contributors could have different / better ideas.

1. The main "intended usage" of Petals is to run models the size of chatGPT (or BLOOM-176B and OPT-175B or ...) by pooling existing idle resources - just like you said. I cannot promise that this will be the best solution, but at least we will try our best to make it so. You can read more on theoretical aspects in [this paper](https://arxiv.org/abs/2209.01188)

2. Ecology-wise, I believe petals can make LLMs more sustainable since it reuses existing GPUs. Instead of producing new hardware to build a new GPU cluster, we can reuse the hardware humans already have, and thus save a lion's share of GPU carbon footprint.

However, it is too early to make any conclusions on what Petals solves or cannot solve. For now all I can say is "we're working on it".

**Comment by justheuristic** [comment]
[Marked as "closed" because this is not a technical bug / feature request. If you want to continue discussion, let us switch to [our discord server](https://discord.com/invite/uGugx9zYvN)]
