### ISSUE TITLE
http://health.petals.ml/ shows "broken" in the same timeframe i spin up a docker petals

### ISSUE THREAD

**Issue by worldpeaceenginelabs** [bigscience-workshop/petals#282]
Hi there.

I think your project is awesome and want to support you by sharing my resources.

I noticed an outage on bloom and bloomz, yesterday when i used a dockercompose to spin up a new docker image.
I noticed a second outage just now on bloom, when i started the colab on https://colab.research.google.com/drive/1Ervk6HPNS6AYVr3xVdQnY5a-TjjmLCdQ?usp=sharing

Maybe its just coincidence, but maybe some script for taking the new node in crashes your config something...?

Just let you know in case.
Thanks for that awesome project.

**Comment by borzunov** [comment]
Hi @worldpeaceenginelabs,

Thanks for the kind words and contributing compute!

I've taken a look on the logs, and I think it's just a coincidence - the swarm occasionally becomes broken because people run servers on cheap spot instances that can be hibernated at any time, or disconnect for a few hours to use their GPU for something else. I hope we'll have less outages once more servers join.

I'll close this issue for now, but feel free to reopen it or create a new one if you meet any other issues.
