### ISSUE TITLE
Open ports needed to connect to the public clusters

### ISSUE THREAD

**Issue by sblaszak** [bigscience-workshop/petals#295]
Hi,

Sorry if this is already mentioned somewhere but I just can't seem to find it.  Are there specific ports that need to be opened on my firewall in order to allow my Petals server(s) to connect to the public cluster?  If so, which ones?

Thanks.

**Comment by borzunov** [comment]
Hi @sblaszak,

For the Petals server, you can choose a TCP port it listens to (e.g. 31330), then add the `--port 31330` argument and allow incoming connections to this port in your firewall. You should also allow outgoing connections to all TCP ports, since other nodes in the network may use arbitrary port numbers + you'd need to send requests to TCP ports 80 and 443 to download model weights from Hugging Face servers.

**Comment by sblaszak** [comment]
Awesome, thanks for the info.

**Comment by borzunov** [comment]
The server also works when the firewall doesn't allow incoming connection (it'll accept connections through libp2p [circuit relays](https://docs.libp2p.io/concepts/nat/circuit-relay/)), but it may be slower in this case.
