### ISSUE TITLE
Decentralized training of large models

### ISSUE THREAD

**Issue by Denintendator** [bigscience-workshop/petals#366]
Not an issue, but there is a question. Have you guys considered doing the same project but for decentralized TRAINING of a model? With this technology open source could create huge models without spending a lot of money on expensive hardware 🤔

**Comment by GravermanDev** [comment]
go to discord and ask it there maybe
https://discord.gg/2XrhGdeF

**Comment by mryab** [comment]
Hi! You should probably be interested in our past work on decentralized training of large models:
* In a 2020 paper, we proposed a way to train large Mixture-of-Experts models with volunteers: https://arxiv.org/abs/2002.04013
* In 2021, we ran a real-world collaborative pretraining experiment and obtained a model for Bengali language representations that was competitive with then-SoTA on this language: https://arxiv.org/abs/2106.10207 and https://huggingface.co/blog/collaborative-training
* We've also trained a text-to-image Transformer model with volunteers in a NeurIPS 2021 demonstration: https://training-transformers-together.github.io/
* Our latest work, [SWARM Parallelism](https://arxiv.org/abs/2301.11913), proposes a way to train large (1B+) language models over the Internet with pipeline parallelism. It shares many similarities with Petals in terms of system design, and we've started work on this even before Petals

All of these results are possible because of Hivemind (https://github.com/learning-at-home/hivemind) — a library for decentralized DL that we have been developing. If you have any questions about decentralized training, I'd be happy to answer them!

**Comment by borzunov** [comment]
Hi @Denintendator,

Please also see Q3 in the "General" section of our FAQ: https://github.com/bigscience-workshop/petals/wiki/FAQ:-Frequently-asked-questions#general It explains how hivemind and petals are different in terms of training models from scratch.
