### ISSUE TITLE
eidt. may already exist in server.py Next Step create a distributed hash table to indicate which IP addresses are hosting which parts of different models rather than using a redis database

### ISSUE THREAD

**Issue by Georgith** [bigscience-workshop/petals#417]
okay I'm editing this because apparently bard made a mistake and analyzed the code and thought it was using a redis database but I am now seeing evidence of a DHT distributed hash table database in server.py 

nonetheless I'm leaving the discussion here as well as the link to the bard chat that I'm having because it may help others we're trying to analyze the code and come up to speed quickly period

Next Step create a distributed hash table to indicate which IP addresses are hosting which parts of different models rather than using a redis database?

I'm querying the code base using Bard and getting suggestions from it as well as explanations of the code base as I'm new to the code base  one of the things that Bard suggested is a distributed hash table so it's less reliant on a centralized database it is a single source of failure.

Here's the link to the bard chat session which I will no doubt continue to expand as I seek to understand this code .

https://g.co/bard/share/5a72c0680eb2

as you can see I'm asking for bar to actually code some python to implement possible distributed hash table Discovery protocols as well as distributed hash tables period I'll confess I am not used to GitHub I'm used to individual coding old school 1990s machines so don't know how to commit to a centralized project Etc but through Bard I'm able to understand this code fairly quickly and I can see it can make some python suggestions fairly quickly and if others follow along with this bard chat or Implement their own bar chats we might be able to really crank up and accelerate the development of this project to a true blockchain oriented distributed hash table system.

**Comment by borzunov** [comment]
Hi @Georgith,

We do not use Redis in our code at all, instead we use [hivemind.DHT](https://github.com/learning-at-home/hivemind) as a distributed hash table storing addresses of available servers.

Please note that Bard does not have access to the Internet and actually [hallucinated](https://machinelearningmastery.com/a-gentle-introduction-to-hallucinations-in-large-language-models/) in its responses (it wrote a "realistic" code that does not actually work, since we don't have `petals.client.Endpoint` classes).

You may overcome hallucinations by feeding Petals code to the LLM directly, but we still **strongly discourage** everyone from analyzing code this way. That's because Petals code is pretty complicated and modern LLMs are not powerful enough to understand it or give any reasonable advice, as we know from people who've tried to analyze the code with ChatGPT before.

**Comment by Georgith** [comment]
Thank you for the response. Yes I did notice that error that Bard made as well. I'll definitely have to be careful using it to analyze any code. Was hoping to get a quick overview and outline of the code with it and it sort of did that but the details were wrong.
