### ISSUE TITLE
GGML + petals

### ISSUE THREAD

**Issue by PaulConyngham** [bigscience-workshop/petals#439]
Hi guys - quick one to ask if there is any roadmap item to add GGML (CPU) supported models to the petals framework. 

As I have a ton of old computers around the house would be amazing to contribute this way, but not sure if CPUs are too slow in general.

GGML would also help bring apple silicon GPU acceleration into the mix too.

Really really appreciate this project. It is amazing and looking forward to seeing where it goes.

**Comment by borzunov** [comment]
Hi @PaulConyngham,

Cross-posting from Discord: I think standard CPUs are too slow, but Apple M1/M2 may be okay to make a reasonable contribution, as our benchmarks in #147 show.

I think it's difficult to move to GGML since we rely on PyTorch + HF transformers stack, so we'd need to rewrite the server from scratch. So instead I would opt for finishing Mac silicon support in the existing code, like we started to do in #147.

Let us know if you have any other questions.
