### ISSUE TITLE
Out of memory on a client with 8 GB RAM

### ISSUE THREAD

**Issue by ryanshrott** [bigscience-workshop/petals#465]
Getting this error using ubuntu. My computer has 8GB of ram. How to fix it?

ryan@ryanubuntu~/Documents$ python3 python_petals.py
Aug 15 16:16:25.365 [INFO] Make sure you follow the LLaMA's terms of use: https://bit.ly/llama2-license for LLaMA 2, https://bit.ly/llama-license for LLaMA 1
Aug 15 16:16:25.365 [INFO] Using DHT prefix: StableBeluga2-hf
Loading checkpoint shards:   0%|                    | 0/2 [00:00<?, ?it/s]Killed

**Comment by ryanshrott** [comment]
I monitored my memory usage and see that I run out of memory :( Is 8gb not enough?

**Comment by borzunov** [comment]
Hi @ryanshrott,

I think the issue is that StableBeluga2 is sharded into large chunks (~10 GB) and the client needs to load at least one chunk into RAM to read the weights, even though it only uses a very small part of the weights (~2.1 GB).

Can you try replacing `stabilityai/StableBeluga2` with `petals-team/StableBeluga2`? This is the repository with the same model sharded into 1 GB chunks that should work smoothly on 8 GB RAM machines.

**Comment by ryanshrott** [comment]
thanks, now i get this warning. is it an issue?
Aug 16 08:16:45.491 [INFO] Route found: 0:33 via …RoKEHa => 33:58 via …G5pJHP => 58:80 via …cjWtUS
Aug 16 08:17:33.951 [WARN] [petals.client.lm_head.chunked_forward:72] Running the client with dtype bfloat16 on CPU may be slow, since your CPU doesn't support AVX512. Consider loading the model with torch_dtype='float32'

**Comment by borzunov** [comment]
@ryanshrott, this means that your code works fine, but it'll work much faster speed if you load the model in float32 (due to your CPU's properties):

```python
model = AutoDistributedModelForCausalLM.from_pretrained(model_name, torch_dtype=torch.float32)
```

Let us know if you have any other issues.
