### ISSUE TITLE
Can petals run a quantized (use GPTQ) llama model ?

### ISSUE THREAD

**Issue by sa1utyeggs** [bigscience-workshop/petals#514]
hello, I'm trying to run a quantized llama model named TheBloke/WizardCoder-Python-34B-V1.0-GPTQ (here is the huggingface url: https://huggingface.co/TheBloke/WizardCoder-Python-34B-V1.0-GPTQ).

And it is based on llama model, I tried to run it on petals, but error occured:
![image](https://github.com/bigscience-workshop/petals/assets/63895563/cef7e63f-50ad-44e3-a0d8-3faee34db22e)

The following is the startup command：
python -m petals.cli.run_server /data/chat/models/WizardCoder-Python-34B-V1.0-GPTQ --dht_prefix WizardCoder-Python-34B-GPTQ  --initial_peers $INITIAL_PEERS --num_blocks 10 --public_name V100-WizardCoder-Python-34B-GPTQ

looking for help.      : )

**Comment by sa1utyeggs** [comment]
Thank you for your answer, But a whole model file is too large to transfer through the Internet.
I wonder is there any chance to divide the whole model file into multiple block files. So, the transportation will be faster and eazier.
Then, every port can only store the blocks they need to economize their storage.
Forwarding to hear your answer. :)

**Comment by borzunov** [comment]
@sa1utyeggs,

This model is already divided into multiple files, and Petals will only download the necessary parts:

<img width="487" alt="Screenshot 2023-09-20 at 02 10 46" src="https://github.com/bigscience-workshop/petals/assets/8748943/59f40f9e-621e-4858-8362-e4ba1fd22001">

Note that these files store the model in 16-bit, and their total size is ~4x larger than the model size in the repo you suggested. Unfortunately, that's necessary for now since Petals can't load a model that is already quantized (we're working on changing that).
