### ISSUE TITLE
Support stable diffusion model

### ISSUE THREAD

**Issue by lbgws2** [bigscience-workshop/petals#519]
can i use stable diffusion model with petals?

**Comment by borzunov** [comment]
Hi @lbgws2,

StableDiffusion usually fits into one GPU, so we recommend to use [StableHorde](https://stablehorde.net/) instead (it's another volunteer computing project focused on smaller models).

We don't plan to support StableDiffusion since Petals is focused on very large models that don't fit into one consumer GPU (so we have to use pipeline parallelism).

**Comment by lbgws2** [comment]
What a surprise！！
thank you very much @borzunov
