### ISSUE TITLE
Unable to connect to Private Swarm

### ISSUE THREAD

**Issue by Rohit-03** [bigscience-workshop/petals#589]
Hi, I have followed the instructions here to [Launch your own swarm](https://github.com/bigscience-workshop/petals/wiki/Launch-your-own-swarm) and I am able to get machine 1 up and running, but when i run the command for machine 2:
(python3 -m petals.cli.run_server bigscience/bloom --initial_peers /ip/172.16.0.2/tcp/31337/p2p/Qmai8PYDczXNvBSqvpNK9AG8PR7C58g4DKQAawdfVGyyGP / ip4/127.0.0.1/tcp/31337/p2p/Qmai8PYDczXNvBSqvpNK9AG8PR7C58g4DKQAawdfVGyyGP)

I get the following error:

<img width="989" alt="PNG image" src="https://github.com/user-attachments/assets/6f6857c8-10da-43cd-994a-40327443b766">

I also saw another resolved issue regarding connecting to a private swarm, (https://github.com/bigscience-workshop/petals/issues/511#issuecomment-1809873702) where a solution was to run the following on machine 2:

--initial_peers /ip4/159.89.214.152/tcp/31337/p2p/QmedTaZXmULqwspJXz44SsPZyTNKxhnnFvYRajfH7MGhCY /ip4/159.203.156.48/tcp/31338/p2p/QmQGTqmM7NKjV6ggU1ZCap8zWiyKR89RViDXiqehSiCpY5

However I am confused about how running this connects to my own private swarm, if a generalized IPV4 address is being used.

**Comment by justheuristic** [comment]
Hi! Depending on your network type, machine 1 typically needs to be configured with port 31337 opened for incoming connections. If you are running over the internet, you need to open the port to the internet, conventionally, If you are running in an internal network, it should be accessible by whatever machine 2 stands for.

There are two ways to test this:
- (a) try running some other service on that port (e.g. jupyter or python -m http.server with proper args). If that server is accessible from machine 2, something is wrong with petals. If it is not accessible, that's a network / ports problem
-  (b) alternatively, try running another node on machine 1 and connect it to the existing node. If it connects from the same machine but not from another machine, the problem is either a closed port or an inaccessible address; If it does not connect from the same machine, something broke with petals/hivemind

Please also note that petals (and hivemind in general) have ways to circumvent opening ports through relays or nat traversal, but they require having a mutually accessible third party with [--use_auto_relay](https://github.com/bigscience-workshop/petals/blob/main/src/petals/cli/run_dht.py#L76C12-L76C26) in the swarm.
